### ISSUE TITLE
auro-library: implement github workflow maintenance scripts

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-library#25] opened 2023-07-18 22:34 UTC
### Is your feature request related to a problem? Please describe.

I spend too much time and effort making sure that the repo I'm working in is up to date with the latest [WC-Generator](https://github.com/AlaskaAirlines/WC-Generator) standards. It would be excellent if there was a script that existed that automatically updated the repo I was working in with the latest repo config standards.

### Describe the solution you'd like

0. Add `standardizeWorkflows.js` or similarly named script to `auro-library` that updates current repos `.github/workflows` directory to match [WC-Generator](https://github.com/AlaskaAirlines/WC-Generator)
1. `cd` into an auro component repo
2. add `auro-library` as a dependency
3. add `"build:repoConfig"` or similar script name that executes `auro-library`'s `standardizeWorkflows.js` to `package.json`  
4. exectute `npm run build:repoConfig` 
5. observe repo had its github workflows updated to match [WC-Generator](https://github.com/AlaskaAirlines/WC-Generator)

### Additional context

This would make an excellent first candidate to use with #18 to propagate the update to all of our repositories

**Comment by Patrick-Daly-AA** [comment] 2023-08-23 20:36
This is a duplicate of #32

**Closed by Patrick-Daly-AA** 2023-08-23 20:36 UTC
Labels: auro-library, not-reviewed, Type: Feature
